name: Run Gradle Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests with Gradle and Java 21
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew test > test-results.txt || echo "Tests failed"

      - name: Parse test results
        if: ${{ failure() }}
        run: |
          echo "Tests failed"
          cat test-results.txt
          else
          echo "All tests passed"