name: Run Gradle Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests with Gradle and Java 21
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}